permalink: /:title

# Variables to configure RSS feed
# https://github.com/jekyll/jekyll-feed
title: YassLab 株式会社
description: "沖縄と東京を拠点にしたソフトウェア開発会社です。RailsチュートリアルやRailsガイドを運営し、月額制開発支援サービスも提供しています。"
author:
  name: YassLab 株式会社
  image: /img/logos/500x500.png
  twitter: YassLab
  facebook: yasslab.jp

# `url` is necessary to generate RSS feed.
# cf. https://github.com/jekyll/jekyll-feed
url: https://yasslab.jp

# Variables for internal use
company:
  vision: "Having a Good Life with OpenSource ;)"
  name:  YassLab
  ja:
    name: YassLab 株式会社
    description: "沖縄と東京を拠点にしたソフトウェア開発会社です。RailsチュートリアルやRailsガイドを運営し、月額制開発支援サービスも提供しています。"
  en:
    name: YassLab Inc.
    description: "100% Remote Work company based in Okinawa & Tokyo, focusing on Ruby/Rails Web Development, Education, and OpenSource."
  email: info@yasslab.jp
  capital: 500
  size: 12
  description: "100% Remote Work company based in Okinawa & Tokyo, focusing on Ruby/Rails Web Development, Education, and OpenSource."

domain:   "yasslab.jp"
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

## Show upcoming posts in development
future: true
excerpt_separator: "続きを読む"

## Global Vars to generate links
yasslab:       "[YassLab](https://yasslab.jp)"
railstutorial: "[Railsチュートリアル](https://railstutorial.jp)"
railsguides:   "[Railsガイド](https://railsguides.jp/)"
coderdojo:     "[CoderDojo Japan](https://coderdojo.jp)"
okinawarb:     "[Okianwa.rb](https://ruby.okinawa)"
frogs:         "[Ryukyufrogs](https://www.ryukyu-frogs.com)"

highlighter: rouge
markdown: kramdown

kramdown:
  auto_ids      : true
  autolink      : true
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  input         : GFM
  gfm_quirks    : paragraph_end
  hard_wrap     : true
  footnote_nr   : 1
  show_warnings : false

plugins: 
  - kramdown
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-feed
  - qiita

exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - test
  - spec

